package mapa;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Leonardo Buta
 */
public class MapaUI extends javax.swing.JFrame {

    int scoreA = 0, scoreB = 0, currentScoreA = 0, currentScoreB = 0;

    /**
     * Creates new form MapaUI
     */
    public MapaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblScoreB = new javax.swing.JLabel();
        lblScoreA = new javax.swing.JLabel();
        lblCurrentScoreB = new javax.swing.JLabel();
        lblCurrentScoreA = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        panelPointsA = new javax.swing.JPanel();
        minutsOnePointA = new javax.swing.JButton();
        onePointA = new javax.swing.JButton();
        threePointA = new javax.swing.JButton();
        panelPointsB = new javax.swing.JPanel();
        minusOnePointB = new javax.swing.JButton();
        onePointB = new javax.swing.JButton();
        threePointB = new javax.swing.JButton();
        lblRestartMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teamA.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teamB.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/score.png"))); // NOI18N

        lblScoreB.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblScoreB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreB.setText("0");

        lblScoreA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblScoreA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreA.setText("0");

        lblCurrentScoreB.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCurrentScoreB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentScoreB.setText("0");

        lblCurrentScoreA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCurrentScoreA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentScoreA.setText("0");

        lblWinner.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblWinner.setText("          ");
        lblWinner.setToolTipText("");

        btnRestart.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restart.png"))); // NOI18N
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        minutsOnePointA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        minutsOnePointA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minusone.png"))); // NOI18N
        minutsOnePointA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutsOnePointAActionPerformed(evt);
            }
        });

        onePointA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        onePointA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onepoint.png"))); // NOI18N
        onePointA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePointAActionPerformed(evt);
            }
        });

        threePointA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        threePointA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3point.png"))); // NOI18N
        threePointA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePointAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPointsALayout = new javax.swing.GroupLayout(panelPointsA);
        panelPointsA.setLayout(panelPointsALayout);
        panelPointsALayout.setHorizontalGroup(
            panelPointsALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPointsALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPointsALayout.createSequentialGroup()
                        .addComponent(onePointA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(threePointA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPointsALayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(minutsOnePointA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelPointsALayout.setVerticalGroup(
            panelPointsALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPointsALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(onePointA)
                    .addComponent(threePointA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minutsOnePointA)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        minusOnePointB.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        minusOnePointB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minusone.png"))); // NOI18N
        minusOnePointB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusOnePointBActionPerformed(evt);
            }
        });

        onePointB.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        onePointB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onepoint.png"))); // NOI18N
        onePointB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePointBActionPerformed(evt);
            }
        });

        threePointB.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        threePointB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3point.png"))); // NOI18N
        threePointB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePointBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPointsBLayout = new javax.swing.GroupLayout(panelPointsB);
        panelPointsB.setLayout(panelPointsBLayout);
        panelPointsBLayout.setHorizontalGroup(
            panelPointsBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsBLayout.createSequentialGroup()
                .addGroup(panelPointsBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPointsBLayout.createSequentialGroup()
                        .addComponent(onePointB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(threePointB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPointsBLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(minusOnePointB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panelPointsBLayout.setVerticalGroup(
            panelPointsBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPointsBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(onePointB)
                    .addComponent(threePointB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minusOnePointB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRestartMessage.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblRestartMessage.setText("           ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualRound.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panelPointsA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnRestart)
                        .addGap(78, 78, 78)
                        .addComponent(panelPointsB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCurrentScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(235, 235, 235)))))
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWinner)
                            .addComponent(lblRestartMessage)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCurrentScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblScoreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScoreB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(lblWinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRestartMessage)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurrentScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrentScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPointsA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelPointsB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRestart, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        lblScoreB.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threePointBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePointBActionPerformed
        currentScoreB += 3;
        lblCurrentScoreB.setText(Integer.toString(currentScoreB));
        updateScore();
    }//GEN-LAST:event_threePointBActionPerformed

    private void onePointBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePointBActionPerformed
        currentScoreB++;
        lblCurrentScoreB.setText(Integer.toString(currentScoreB));
        updateScore();
    }//GEN-LAST:event_onePointBActionPerformed

    private void minusOnePointBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusOnePointBActionPerformed
        currentScoreB--;
        lblCurrentScoreB.setText(Integer.toString(currentScoreB));
        updateScore();
    }//GEN-LAST:event_minusOnePointBActionPerformed

    private void threePointAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePointAActionPerformed
        currentScoreA += 3;
        lblCurrentScoreA.setText(Integer.toString(currentScoreA));
        updateScore();
    }//GEN-LAST:event_threePointAActionPerformed

    private void onePointAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePointAActionPerformed
        currentScoreA++;
        lblCurrentScoreA.setText(Integer.toString(currentScoreA));
        updateScore();
    }//GEN-LAST:event_onePointAActionPerformed

    private void minutsOnePointAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutsOnePointAActionPerformed
        currentScoreA--;
        lblCurrentScoreA.setText(Integer.toString(currentScoreA));
        updateScore();
    }//GEN-LAST:event_minutsOnePointAActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        resetScore();
        resetCurrentScore();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void updateScore() {
        if (currentScoreA >= 12) {
            scoreA++;
            lblScoreA.setText(Integer.toString(scoreA));
            resetCurrentScore();
        } else if (currentScoreB >= 12) {
            scoreB++;            
            lblScoreB.setText(Integer.toString(scoreB));
            resetCurrentScore();
        }
        
        if (scoreA >= 2){
            toggleScoreButtons(false);
            lblWinner.setText("O Vencedor é a equipe A!");
            lblRestartMessage.setText("Clique em reiniciar para começar novamente");
        }else if (scoreB >= 2){
            toggleScoreButtons(false);
            lblWinner.setText("O Vencedor é a equipe B!");
            lblRestartMessage.setText("Clique em reiniciar para começar novamente");
        }
    }
    
    private void resetCurrentScore(){
        currentScoreA = 0;
        currentScoreB = 0;
        lblCurrentScoreA.setText(Integer.toString(currentScoreA));
        lblCurrentScoreB.setText(Integer.toString(currentScoreB));
    }
    
    private void resetScore(){
        scoreA = 0;
        scoreB = 0;
        lblScoreA.setText(Integer.toString(scoreA));
        lblScoreB.setText(Integer.toString(scoreB));
        toggleScoreButtons(true);
        lblWinner.setText("");
        lblRestartMessage.setText("");
    }
    
    private void toggleScoreButtons(boolean enable) {
        for (Component cp : panelPointsA.getComponents()) {
            cp.setEnabled(enable);
        }
        
        for (Component cp : panelPointsB.getComponents()) {
            cp.setEnabled(enable);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MapaUI frame = new MapaUI();
                frame.setTitle("Pontuação Jogo de Cartas");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/cards.png")));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrentScoreA;
    private javax.swing.JLabel lblCurrentScoreB;
    private javax.swing.JLabel lblRestartMessage;
    private javax.swing.JLabel lblScoreA;
    private javax.swing.JLabel lblScoreB;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JButton minusOnePointB;
    private javax.swing.JButton minutsOnePointA;
    private javax.swing.JButton onePointA;
    private javax.swing.JButton onePointB;
    private javax.swing.JPanel panelPointsA;
    private javax.swing.JPanel panelPointsB;
    private javax.swing.JButton threePointA;
    private javax.swing.JButton threePointB;
    // End of variables declaration//GEN-END:variables
}
